app/models/location.py
from app import db
import enum

class LocationType(enum.Enum):
	PROVINCENODE = 'Province Node'
	WAREHOUSE = 'Warehouse'


class LocationRegion(enum.Enum):
	CENTRAL = 'Central'
	EAST = 'East'
	NORTHEAST = 'North East'
	WEST = 'West'
	def __repr__(self):
		return '<Region: name=%r, value=%r>' % (name, value)


class Location(db.Model):
	id = db.Column(db.String(20), primary_key=True, nullable=False)
	name = db.Column(db.String(30), nullable=False)
	type = db.Column(db.Enum(LocationType), nullable=False)
	region = db.Column(db.Enum(LocationRegion), nullable=False)
	province = db.Column(db.String(50))
	district = db.Column(db.String(50))
	zipcode = db.Column(db.String(5))
	description = db.Column(db.Text)
	comment = db.Column(db.Text)

	creator_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)
	creator = db.relationship('User')
	projects = db.relationship("ProjectLocation", lazy='dynamic')

	def __init__(self, id, name, creator, type=LocationType.PROVINCENODE, region=None, province=None, district=None, zipcode=None, description=None, comment=None):
		 self.id = id
		 self.name = name
		 self.type = type
		 self.region = region
		 self.province = province
		 self.district = district
		 self.zipcode = zipcode
		 self.description = description
		 self.comment = comment
		 self.creator = creator

	def __repr__(self):
		return '<Location id={}, name={}, type={}>'.format(self.id, self.name, self.type.value)

app/views/item.py
from flask import render_template, abort, redirect, request, url_for, Blueprint
import flask_login
from app import app, db, login_manager, upload_file
from app.models import Item, Project, Order ,ItemFile, ItemLocation, IndexWarrantyType
from app.forms import LocationForm, UploadFileForm, ItemForm


item = Blueprint('item', __name__)


#--- Detail ---
@item.route('/<id>/', methods=['GET'])
@flask_login.login_required
def item_detail(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if not item:
        abort(404)    
    return render_template('item/detail.html', item=item, page='material')


@item.route('/<id>/edit', methods=['GET', 'POST'])
@flask_login.login_required
def item_detail_edit(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if request.method == 'GET':
        form = ItemForm(obj=item)
        choices = [(c.id, c.name) for c in IndexWarrantyType.query.order_by(IndexWarrantyType.name).all()]
        form.warranty_type.choices = choices
        form.warranty_type.process_data(item.warranty_type.id)
        warranty_types = IndexWarrantyType.query.all()
        return render_template('item/edit.html', item=item, warranty_types=warranty_types, form=form, page='material')
    
    form = ItemForm(request.form)
    if request.method == 'POST':
        item.box_number = form.box_number.data
        item.name = form.name.data
        item.warranty_type_id = form.warranty_type.data
        item.warranty_expire = form.warranty_expire.data
        item.sap = form.sap.data
        db.session.merge(item)
        db.session.commit()
    return redirect(url_for('item.item_detail', id=item.serial_number))


# --- Project ---
@item.route('/<id>/project', methods=['GET'])
@flask_login.login_required
def item_project(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if not item:
        abort(404)
    return render_template('item/project.html', item=item, page='material')


# --- Location ---
@item.route('/<id>/location', methods=['GET'])
@flask_login.login_required
def item_location(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    locations = ItemLocation.query.filter_by(item_serial_number=id).all()
    if not item:
        abort(404)
    return render_template('item/location.html', item=item, locations=locations, page='material')


# --- File ---
@item.route('/<id>/file', methods=['GET'])
@flask_login.login_required
def item_files(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if not item:
        abort(404)
    files = item.files.all()
    return render_template('item/file.html', item=item, files=files, page='material')



@item.route('/<id>/file/upload', methods=['GET', 'POST'])
@flask_login.login_required
def item_file_upload(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    form = UploadFileForm(request.form)
    if request.method == 'GET':
        return render_template('item/upload.html', form=form, item=item, page='material')

    if request.method == 'POST':
        file = request.files.get('afile')
        description = request.form.get('description')
        original_name, hash_name = upload_file(file)
        itemfile = ItemFile(name=original_name,
                            object_name=hash_name,
                            type=form.type.data,
                            description=form.description.data,
                            serial=item,
                            uploader=flask_login.current_user)
        db.session.add(itemfile)
        db.session.commit()
    return redirect(url_for('item.item_files', id=item.serial_number))

app/views/location.py
from flask import render_template, abort, redirect, request, url_for, Blueprint
import flask_login
from app import app, db, login_manager
from app.models import Location, LocationType, LocationRegion
from app.forms import LocationForm


location = Blueprint('location', __name__)


@location.route('/', methods=['GET'])
@flask_login.login_required
def index():
    locations = Location.query.all()
    return render_template('location/index.html', locations=locations, page='location')


@location.route('/<id>/', methods=['GET', 'POST'])
@flask_login.login_required
def detail(id=None):
    location = Location.query.filter_by(id=id).first()
    return render_template('location/detail.html', location=location, page='location')


@location.route('/add', methods=['GET', 'POST'])
def create():
    form = LocationForm(request.form)
    if request.method == 'GET':
        return render_template('location/add.html', form=form, page='location')
    if request.method == 'POST':
        location = Location(id = form.id.data,
                            name = form.name.data,
                            type = form.type.data,
                            region = form.region.data,
                            province = form.province.data,
                            district = form.district.data,
                            zipcode = form.zipcode.data,
                            description = form.description.data,
                            comment = form.comment.data,
                            creator=flask_login.current_user)
        db.session.add(location)
        db.session.commit()
    return redirect(url_for('location.index'))


@location.route('/<id>/edit', methods=['GET', 'POST'])
@flask_login.login_required
def edit(id=None):
    location = Location.query.filter_by(id=id).first()
    if not location:
        abort(404)

    if request.method == 'GET':
        form = LocationForm(obj=location)
        return render_template('location/edit.html', location=location, form=form, page='location')
    
    form = LocationForm(request.form)
    if request.method == 'POST':
        location.name = form.name.data
        location.type = form.type.data
        location.region = form.region.data
        location.province = form.province.data
        location.district = form.district.data
        location.zipcode = form.zipcode.data
        location.description = form.description.data
        location.comment = form.comment.data
        db.session.merge(location)
        db.session.commit()
    return redirect(url_for('location.detail', id=location.id))

app/views/project.py
from flask import render_template, abort, redirect, request, url_for, Blueprint, abort
import flask_login
from app import app, db, login_manager, upload_file
from app.models import Project, ProjectFile, ProjectMember, ProjectLocation, Customer, Order, Item,\
                    ItemLocation, ItemStatus, MaterialType, ProjectFileType, IndexWarrantyType, Material, Location
from app.forms import ProjectForm, OrderForm, CustomerForm, UploadForm, ItemForm
import datetime

project = Blueprint('project', __name__)


@project.route('/', methods=['GET'])
@flask_login.login_required
def index():
    projects = Project.query.all()
    user = flask_login.current_user
    return render_template('project/index.html', user=user, projects=projects, page='project')


# --- Create ---
@project.route('/create', methods=['GET', 'POST'])
@flask_login.login_required
def create():
    form = ProjectForm(request.form)
    if request.method == 'GET':
        return render_template('project/add.html', form=form, page='project')
        
    if request.method == 'POST':
        project = Project(id=form.id.data, 
                        name=form.name.data, 
                        description=form.description.data, 
                        goal=form.goal.data,
                        progress=form.progress.data, 
                        agreement=form.agreement.data,
                        status=form.status.data,
                        creator=flask_login.current_user,
                        updated_time=str(datetime.datetime.utcnow()))
        db.session.add(project)
        db.session.commit()
    return redirect(url_for('project.index'))


# --- Detail ---
@project.route('/<id>', methods=['GET'])
@flask_login.login_required
def get(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/detail/index.html', project=project, page='project')


@project.route('/<id>/detail/edit', methods=['GET', 'POST'])
@flask_login.login_required
def detail_edit(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    
    if request.method == 'GET':
        form = ProjectForm(obj=project)
        return render_template('project/detail/edit.html', project=project, form=form, page='project')
    
    form = ProjectForm(request.form)
    if request.method == 'POST':
        project.name = form.name.data
        project.description = form.description.data
        project.updated_time = str(datetime.datetime.utcnow())
        db.session.merge(project)
        db.session.commit()
    return redirect(url_for('project.get', id=project.id))


# --- Order ---
@project.route('/<id>/order', methods=['GET'])
@flask_login.login_required
def order(id=None):
    project = Project.query.filter_by(id=id).first()
    orders = Order.query.filter_by(project=project).all()
    return render_template('project/order/index.html', project=project, orders=orders, page='project')


@project.route('/<id>/order/add', methods=['GET', 'POST'])
@flask_login.login_required
def order_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = OrderForm(request.form)
    if request.method == 'GET':
        return render_template('project/order/add.html', form=form, page='project')

    if request.method == 'POST':
        order = Order(number=form.number.data,
                    project=project,
                    description=form.description.data,
                    bill_of_material=form.bill_of_material.data,
                    vendor=form.vendor.data,
                    creator=flask_login.current_user)
        db.session.add(order)
        db.session.commit()
    return redirect(url_for('project.order', id=project.id))


@project.route('/<id>/order/edit', methods=['GET', 'POST'])
@flask_login.login_required
def order_edit(id=None):
    return render_template('project/order/edit.html', project=project, page='project')


# --- Customer ---
@project.route('/<id>/customer', methods=['GET'])
@flask_login.login_required
def customer(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    customers = Customer.query.filter_by(project=project).all()
    return render_template('project/customer/index.html', project=project, customers=customers, page='project')


@project.route('/<id>/customer/add', methods=['GET', 'POST'])
@flask_login.login_required
def customer_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = CustomerForm(request.form)
    if request.method == 'GET':
        return render_template('project/customer/add.html', form=form, page='project')

    if request.method == 'POST':
        customer = Customer(firstname=form.firstname.data,
                            lastname=form.lastname.data,
                            location=form.location.data,
                            telephone=form.telephone.data,
                            email=form.email.data,
                            description=form.description.data,
                            project=project,
                            creator=flask_login.current_user)
        
        db.session.add(customer)
        db.session.commit()
    return redirect(url_for('project.customer', id=project.id))


# --- Member ---
@project.route('/<id>/member', methods=['GET'])
@flask_login.login_required
def member(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    members = ProjectMember.query.filter_by(project=project).all()
    return render_template('project/member/index.html', project=project, members=members, page='project')


@project.route('/<id>/member/manage', methods=['GET'])
@flask_login.login_required
def member_manage(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/member/manage.html', project=project, page='project')


@project.route('/<id>/member/add', methods=['GET'])
@flask_login.login_required
def member_add(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/member/add.html', project=project, page='project')


# --- Item ---
@project.route('/<id>/item', methods=['GET'])
@flask_login.login_required
def item(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    orders = project.orders.all()
    materials = MaterialType.query.all()
    itemlocation = ItemLocation.query.all()
    return render_template('project/item/index.html', project=project, orders=orders, materials=materials, itemlocation=itemlocation, page='project')


@project.route('/<id>/item/add', methods=['GET', 'POST'])
@flask_login.login_required
def item_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = ItemForm(request.form)
    if not project:
        abort(404)
    
    choices = [(b.number, b.model) for b in Material.query.order_by(Material.model).all()]
    form.material.choices = choices
    materials = Material.query.all()
    
    choices = [(c.id, c.number) for c in Order.query.filter_by(project_id=id).all()]
    form.order.choices = choices
    orders = Order.query.all()

    choices = [(d.id, d.name) for d in IndexWarrantyType.query.order_by(IndexWarrantyType.name).all()]
    form.warranty_type.choices = choices
    warranty_types = IndexWarrantyType.query.all()

    # choices = [(e.id, e.name) for e in ProjectLocation.query.filter_by(project=id).all()]
    choices = [(e.id, e.name) for e in Location.query.order_by(Location.name).all()]
    form.location.choices = choices
    locations = IndexWarrantyType.query.all()
    if request.method == 'GET':
        return render_template('project/item/add.html', form=form, materials=materials, orders=orders, warranty_types=warranty_types, locations=locations, page='project')

    if request.method == 'POST':
        material = Material.query.filter_by(number=form.material.data).first()
        order = Order.query.filter_by(id=form.order.data).first()
        warranty_type = IndexWarrantyType.query.filter_by(id=form.warranty_type.data).first()
        location = Location.query.filter_by(id=form.location.data).first()
        item = Item(serial_number=form.serial_number.data,
                    box_number=form.box_number.data,
                    name=form.name.data,
                    warranty_expire=form.warranty_expire.data,
                    sap=form.sap.data,
                    material=material,
                    order=order,
                    warranty_type=warranty_type)
        
        itemlocation = ItemLocation(location=location,
                                    item=item,
                                    status=form.status.data,
                                    equipment=form.equipment.data,
                                    creator=flask_login.current_user)
        print '<location: {}, item: {}>'.format(location.id, item.serial_number)
        db.session.add(item)
        db.session.add(itemlocation)
        db.session.commit()
    return redirect(url_for('project.item', id=project.id))

# @project.route('/<id>/item/setting', methods=['GET'])
# @flask_login.login_required
# def item_setting(id=None):
#     project = Project.query.filter_by(id=id).first()
#     if not project:
#         abort(404)
#     items = Order.query.filter_by(project=project).all()
#     return render_template('project/item/setting.html', project=project, items=items, page='project')


# --- Location ---
@project.route('/<id>/location', methods=['GET'])
@flask_login.login_required
def location(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    locations = ProjectLocation.query.filter_by(project=project).all()

app/templates/item/detail.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tab-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="javascript:void(0);">Detail</a></li>
                        <li><a href="{{url_for('item.item_project', id=item.serial_number)}}">Project</a></li>
                        <li><a href="{{url_for('item.item_location', id=item.serial_number)}}">Location</a></li>
                        <li><a href="{{url_for('item.item_files', id=item.serial_number)}}">Files</a></li>
                    </ul>

                    <div class="tab-content">
                        <div id="detail" class="tab-pane active cont">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <a href="{{ url_for('item.item_detail_edit', id=item.serial_number) }}" class="btn btn-primary btn-space pull-right" role="button">Edit</a>
                                    <span><h3>Item #{{item.serial_number}}</h3></span>
                                </div>
                                <div class="panel-body">
                                    <form class="form-horizontal group-border-dashed">
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Serial Number</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.serial_number}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Box Number</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.box_number}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>IP Address</b></label>
                                            <div class="col-sm-6">
                                                {% for item_ip in item.ip %}
                                                <p class="form-control-static">{{item_ip.ip_address}}</p>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Port</b></label>
                                            <div class="col-sm-6">
                                                {% for item_ip in item.ip %}
                                                <p class="form-control-static">{{item_ip.port}}</p>
                                                {% endfor %}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>SAP Number</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.sap}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Material Number</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.material_number}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Type</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.material.type.name}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Brand</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.material.brand.name}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Warranty Type</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.warranty_type.name}}</p>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label"><b>Warranty Expire</b></label>
                                            <div class="col-sm-6">
                                                <p class="form-control-static">{{item.warranty_expire}}</p>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/item/file.html
<!-- extend base layout -->
{% extends "base.html" %}


 
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tab-container">
                    <ul class="nav nav-tabs">
                        <li><a href="{{url_for('item.item_detail', id=item.serial_number)}}">Detail</a></li>
                        <li><a href="{{url_for('item.item_project', id=item.serial_number)}}">Project</a></li>
                        <li><a href="{{url_for('item.item_location', id=item.serial_number)}}">Location</a></li>
                        <li class="active"><a href="javascript:void(0);">Files</a></li>
                    </ul>

                    <div class="tab-content">
                        <div id="member" class="tab-pane active cont">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                     <a href="{{ url_for('item.item_file_upload', id=item.serial_number) }}" class="btn btn-primary pull-right" role="button">Upload</a>
                                    <span><h3>Item #{{item.serial_number}}</h3></span>
                                </div>
                                    <div class="form-group">
                                    <label class="col-sm-3 control-label"></label>
                                    <div class="col-sm-6">
                                        <div id="new-search-area" class="text-center"></div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <form action="#" novalidate="" class="form-horizontal group-border-dashed">
                                        <table id="table" class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>File Name</th>
                                                    <th>Type</th>
                                                    <th>Uploader</th>
                                                    <th>Uploaded Date</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for file in files %}
                                                <tr>
                                                    <td><a href="/uploads/{{file.object_name}}">{{file.name}}</a></td>
                                                    <td>{{file.type.value}}</td>
                                                    <td>{{file.uploader.fullname}}</td>
                                                    <td>{{file.uploaded_time}}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/item/location.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tab-container">
                    <ul class="nav nav-tabs">
                        <li><a href="{{url_for('item.item_detail', id=item.serial_number)}}">Detail</a></li>
                        <li><a href="{{url_for('item.item_project', id=item.serial_number)}}">Project</a></li>
                        <li class="active"><a href="javascript:void(0);">Location</a></li>
                        <li><a href="{{url_for('item.item_files', id=item.serial_number)}}">Files</a></li>
                    </ul>

                    <div class="tab-content">
                        <div id="member" class="tab-pane active cont">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <span><h3>Item #{{item.serial_number}}</h3></span>
                                </div>
                                    <div class="form-group">
                                    <label class="col-sm-3 control-label"></label>
                                    <div class="col-sm-6">
                                        <div id="new-search-area" class="text-center"></div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <form action="#" novalidate="" class="form-horizontal group-border-dashed">
                                        <table id="table" class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Location</th>
                                                    <th>Status</th>
                                                    <th>Equipment</th>
                                                    <th>Created by</th>
                                                    <th>Created Time</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for location in locations %}
                                                <tr>
                                                    <td>{{location.location_id}}</td>
                                                    <td>{{location.status.value}}</td>
                                                    <td>{{location.equipment}}</td>
                                                    <td>{{location.creator.fullname}}</td>
                                                    <td>{{location.updated_time}}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}