app/views/item.py
from flask import render_template, abort, redirect, request, url_for, Blueprint
import flask_login
from app import app, db, login_manager, upload_file
from app.models import Item, Project, Order ,ItemFile, ItemLocation, IndexWarrantyType
from app.forms import LocationForm, UploadFileForm, ItemForm


item = Blueprint('item', __name__)


#--- Detail ---
@item.route('/<id>/', methods=['GET'])
@flask_login.login_required
def item_detail(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if not item:
        abort(404)    
    return render_template('item/detail.html', item=item, page='material')


@item.route('/<id>/edit', methods=['GET', 'POST'])
@flask_login.login_required
def item_detail_edit(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if request.method == 'GET':
        form = ItemForm(obj=item)
        choices = [(c.id, c.name) for c in IndexWarrantyType.query.order_by(IndexWarrantyType.name).all()]
        form.warranty_type.choices = choices
        form.warranty_type.process_data(item.warranty_type.id)
        warranty_types = IndexWarrantyType.query.all()
        return render_template('item/edit.html', item=item, warranty_types=warranty_types, form=form, page='material')
    
    form = ItemForm(request.form)
    if request.method == 'POST':
        item.box_number = form.box_number.data
        item.name = form.name.data
        item.warranty_type_id = form.warranty_type.data
        item.warranty_expire = form.warranty_expire.data
        item.sap = form.sap.data
        db.session.merge(item)
        db.session.commit()
    return redirect(url_for('item.item_detail', id=item.serial_number))


# --- Project ---
@item.route('/<id>/project', methods=['GET'])
@flask_login.login_required
def item_project(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if not item:
        abort(404)
    return render_template('item/project.html', item=item, page='material')


# --- Location ---
@item.route('/<id>/location', methods=['GET'])
@flask_login.login_required
def item_location(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    locations = ItemLocation.query.filter_by(item_serial_number=id).all()
    if not item:
        abort(404)
    return render_template('item/location.html', item=item, locations=locations, page='material')


# --- File ---
@item.route('/<id>/file', methods=['GET'])
@flask_login.login_required
def item_files(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    if not item:
        abort(404)
    files = item.files.all()
    return render_template('item/file.html', item=item, files=files, page='material')



@item.route('/<id>/file/upload', methods=['GET', 'POST'])
@flask_login.login_required
def item_file_upload(id=None):
    item = Item.query.filter_by(serial_number=id).first()
    form = UploadFileForm(request.form)
    if request.method == 'GET':
        return render_template('item/upload.html', form=form, item=item, page='material')

    if request.method == 'POST':
        file = request.files.get('afile')
        description = request.form.get('description')
        original_name, hash_name = upload_file(file)
        itemfile = ItemFile(name=original_name,
                            object_name=hash_name,
                            type=form.type.data,
                            description=form.description.data,
                            serial=item,
                            uploader=flask_login.current_user)
        db.session.add(itemfile)
        db.session.commit()
    return redirect(url_for('item.item_files', id=item.serial_number))

app/views/project.py
from flask import render_template, abort, redirect, request, url_for, Blueprint, abort
import flask_login
from app import app, db, login_manager, upload_file
from app.models import Project, ProjectFile, ProjectMember, ProjectLocation, Customer, Order, Item,\
                    ItemLocation, ItemStatus, MaterialType, ProjectFileType, IndexWarrantyType, Material, Location
from app.forms import ProjectForm, OrderForm, CustomerForm, UploadForm, ItemForm
import datetime

project = Blueprint('project', __name__)


@project.route('/', methods=['GET'])
@flask_login.login_required
def index():
    projects = Project.query.all()
    user = flask_login.current_user
    return render_template('project/index.html', user=user, projects=projects, page='project')


# --- Create ---
@project.route('/create', methods=['GET', 'POST'])
@flask_login.login_required
def create():
    form = ProjectForm(request.form)
    if request.method == 'GET':
        return render_template('project/add.html', form=form, page='project')
        
    if request.method == 'POST':
        project = Project(id=form.id.data, 
                        name=form.name.data, 
                        description=form.description.data, 
                        goal=form.goal.data,
                        progress=form.progress.data, 
                        agreement=form.agreement.data,
                        status=form.status.data,
                        creator=flask_login.current_user,
                        updated_time=str(datetime.datetime.utcnow()))
        db.session.add(project)
        db.session.commit()
    return redirect(url_for('project.index'))


# --- Detail ---
@project.route('/<id>', methods=['GET'])
@flask_login.login_required
def get(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/detail/index.html', project=project, page='project')


@project.route('/<id>/detail/edit', methods=['GET', 'POST'])
@flask_login.login_required
def detail_edit(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    
    if request.method == 'GET':
        form = ProjectForm(obj=project)
        return render_template('project/detail/edit.html', project=project, form=form, page='project')
    
    form = ProjectForm(request.form)
    if request.method == 'POST':
        project.name = form.name.data
        project.description = form.description.data
        project.updated_time = str(datetime.datetime.utcnow())
        db.session.merge(project)
        db.session.commit()
    return redirect(url_for('project.get', id=project.id))


# --- Order ---
@project.route('/<id>/order', methods=['GET'])
@flask_login.login_required
def order(id=None):
    project = Project.query.filter_by(id=id).first()
    orders = Order.query.filter_by(project=project).all()
    return render_template('project/order/index.html', project=project, orders=orders, page='project')


@project.route('/<id>/order/add', methods=['GET', 'POST'])
@flask_login.login_required
def order_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = OrderForm(request.form)
    if request.method == 'GET':
        return render_template('project/order/add.html', form=form, page='project')

    if request.method == 'POST':
        order = Order(number=form.number.data,
                    project=project,
                    description=form.description.data,
                    bill_of_material=form.bill_of_material.data,
                    vendor=form.vendor.data,
                    creator=flask_login.current_user)
        db.session.add(order)
        db.session.commit()
    return redirect(url_for('project.order', id=project.id))


@project.route('/<id>/order/edit', methods=['GET', 'POST'])
@flask_login.login_required
def order_edit(id=None):
    return render_template('project/order/edit.html', project=project, page='project')


# --- Customer ---
@project.route('/<id>/customer', methods=['GET'])
@flask_login.login_required
def customer(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    customers = Customer.query.filter_by(project=project).all()
    return render_template('project/customer/index.html', project=project, customers=customers, page='project')


@project.route('/<id>/customer/add', methods=['GET', 'POST'])
@flask_login.login_required
def customer_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = CustomerForm(request.form)
    if request.method == 'GET':
        return render_template('project/customer/add.html', form=form, page='project')

    if request.method == 'POST':
        customer = Customer(firstname=form.firstname.data,
                            lastname=form.lastname.data,
                            location=form.location.data,
                            telephone=form.telephone.data,
                            email=form.email.data,
                            description=form.description.data,
                            project=project,
                            creator=flask_login.current_user)
        
        db.session.add(customer)
        db.session.commit()
    return redirect(url_for('project.customer', id=project.id))


# --- Member ---
@project.route('/<id>/member', methods=['GET'])
@flask_login.login_required
def member(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    members = ProjectMember.query.filter_by(project=project).all()
    return render_template('project/member/index.html', project=project, members=members, page='project')


@project.route('/<id>/member/manage', methods=['GET'])
@flask_login.login_required
def member_manage(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/member/manage.html', project=project, page='project')


@project.route('/<id>/member/add', methods=['GET'])
@flask_login.login_required
def member_add(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/member/add.html', project=project, page='project')


# --- Item ---
@project.route('/<id>/item', methods=['GET'])
@flask_login.login_required
def item(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    orders = project.orders.all()
    materials = MaterialType.query.all()
    itemlocation = ItemLocation.query.all()
    return render_template('project/item/index.html', project=project, orders=orders, materials=materials, itemlocation=itemlocation, page='project')


@project.route('/<id>/item/add', methods=['GET', 'POST'])
@flask_login.login_required
def item_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = ItemForm(request.form)
    if not project:
        abort(404)
    
    choices = [(b.number, b.model) for b in Material.query.order_by(Material.model).all()]
    form.material.choices = choices
    materials = Material.query.all()
    
    choices = [(c.id, c.number) for c in Order.query.filter_by(project_id=id).all()]
    form.order.choices = choices
    orders = Order.query.all()

    choices = [(d.id, d.name) for d in IndexWarrantyType.query.order_by(IndexWarrantyType.name).all()]
    form.warranty_type.choices = choices
    warranty_types = IndexWarrantyType.query.all()

    # choices = [(e.id, e.name) for e in ProjectLocation.query.filter_by(project=id).all()]
    choices = [(e.id, e.name) for e in Location.query.order_by(Location.name).all()]
    form.location.choices = choices
    locations = IndexWarrantyType.query.all()
    if request.method == 'GET':
        return render_template('project/item/add.html', form=form, materials=materials, orders=orders, warranty_types=warranty_types, locations=locations, page='project')

    if request.method == 'POST':
        material = Material.query.filter_by(number=form.material.data).first()
        order = Order.query.filter_by(id=form.order.data).first()
        warranty_type = IndexWarrantyType.query.filter_by(id=form.warranty_type.data).first()
        location = Location.query.filter_by(id=form.location.data).first()
        item = Item(serial_number=form.serial_number.data,
                    box_number=form.box_number.data,
                    name=form.name.data,
                    warranty_expire=form.warranty_expire.data,
                    sap=form.sap.data,
                    material=material,
                    order=order,
                    warranty_type=warranty_type)
        
        itemlocation = ItemLocation(location=location,
                                    item=item,
                                    status=form.status.data,
                                    equipment=form.equipment.data,
                                    creator=flask_login.current_user)
        print '<location: {}, item: {}>'.format(location.id, item.serial_number)
        db.session.add(item)
        db.session.add(itemlocation)
        db.session.commit()
    return redirect(url_for('project.item', id=project.id))

# @project.route('/<id>/item/setting', methods=['GET'])
# @flask_login.login_required
# def item_setting(id=None):
#     project = Project.query.filter_by(id=id).first()
#     if not project:
#         abort(404)
#     items = Order.query.filter_by(project=project).all()
#     return render_template('project/item/setting.html', project=project, items=items, page='project')


# --- Location ---
@project.route('/<id>/location', methods=['GET'])
@flask_login.login_required
def location(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    locations = ProjectLocation.query.filter_by(project=project).all()

app/templates/project/item/add.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><h3>Add Item</h3></span>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal group-border-dashed" method="POST">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Order</label>
                                <div class="col-sm-6">
                                    {{ form.order(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Model</label>
                                <div class="col-sm-6">
                                    {{ form.material(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Serial Number</label>
                                <div class="col-sm-6">
                                    {{ form.serial_number(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Box Number</label>
                                <div class="col-sm-6">
                                    {{ form.box_number(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-6">
                                    {{ form.name(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">SAP Number</label>
                                <div class="col-sm-6">
                                    {{ form.sap(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Warranty Type</label>
                                <div class="col-sm-6">
                                    {{ form.warranty_type(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Warranty Expire</label>
                                <div class="col-sm-6">
                                    {{ form.warranty_expire(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Location</label>
                                <div class="col-sm-6">
                                    {{ form.location(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Status</label>
                                <div class="col-sm-6">
                                    {{ form.status(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Equipment</label>
                                <div class="col-sm-6">
                                    {{ form.equipment(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/project/item/index.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tab-container">
                    <ul class="nav nav-tabs">
                        <li><a href="{{url_for('project.get', id=project.id)}}">Detail</a></li>
                        <li><a href="{{url_for('project.order', id=project.id)}}">Orders</a></li>
                        <li><a href="{{url_for('project.customer', id=project.id)}}">Customers</a></li>
                        <li><a href="{{url_for('project.member', id=project.id)}}">Members</a></li>
                        <li class="active"><a href="javascript:void(0);">Items</a></li>
                        <li><a href="{{url_for('project.location', id=project.id)}}">Locations</a></li>
                        <li><a href="{{url_for('project.files', id=project.id)}}">Files</a></li>
                    </ul>
                    
                    <div class="tab-content">
                        <div id="item" class="tab-pane active cont">
                            <div class="panel-heading">
                                <a href="{{url_for('project.item_add', id=project.id)}}" class="btn btn-primary pull-right" role="button">Add</a>
                                <span><h3>{{project.name}} #{{project.id}}</h3></span>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label"></label>
                                        <div class="col-sm-6">
                                            <div id="new-search-area" class="text-center"></div>
                                        </div>
                                    </div>
                                    <table id="table" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Item</th>
                                                <th>Box Serial</th>
                                                <th>Serial Number</th>
                                                <th>Location</th>
                                                <th>IP Address</th>
                                                <th>Material Number</th>
                                                <th>Type</th>
                                                <th>Status</th>
                                                <th>Equipment</th>
                                                <th>SAP</th>
                                                <th>Product Order</th>
                                                <th>Warranty Type</th>
                                                <th>Warranty Expire</th>
                                                <th>Updated Time</th>
                                                <th>Creator</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for order in orders %}
                                                {% for item in order.items %}
                                                    <tr>
                                                        <td><a href="{{ url_for('item.item_detail', id=item.serial_number) }}">{{item.name}}</a></td>
                                                        <td>{{item.box_number}}</td>
                                                        <td>{{item.serial_number}}</td>
                                                        <td>
                                                            {% if item.latest_item_location.location %}
                                                                {{item.latest_item_location.location.name}}
                                                            {% else %}
                                                                -
                                                            {% endif %}
                                                        </td>
                                                        <td>
                                                            {% for ip in item.ip %}
                                                                {{ip.ip_address}}:{{ip.port}} <br>
                                                            {% endfor %}
                                                        </td>
                                                        <td>{{item.material.number}}</td>
                                                        <td bgcolor="{{item.material.type.cell_color}}" style="color:{{item.material.type.font_color}}">{{item.material.type.name}}</td>
                                                        <td bgcolor="{{item.latest_item_location.cell_color}}">{{item.latest_item_location.status.value}}</td>
                                                        <td>
                                                            {{item.latest_item_location.equipment}}
                                                        </td>
                                                        <td>{{item.sap}}</td>
                                                        <td>{{item.order.number}}</td>
                                                        <td>{{item.warranty_type.name}}</td>
                                                        <td>{{item.warranty_expire}}</td>
                                                        <td>
                                                            {{item.latest_item_location.updated_time}}
                                                        </td>
                                                        <td>
                                                            {% if item.latest_item_location.creator %}
                                                                {{item.latest_item_location.creator.fullname}}
                                                            {% else %}
                                                                -
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}