app/models/order.py
from app import db
import datetime

class Order(db.Model):
	id = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
	number = db.Column(db.String(15), nullable=False)
	bill_of_material = db.Column(db.String(15), nullable=False)
	vendor = db.Column(db.String(50), nullable=False)
	description = db.Column(db.Text)

	creator_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)
	creator = db.relationship('User')
	created_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)

	project_id = db.Column(db.String(15), db.ForeignKey('project.id'), nullable=False)
	project = db.relationship("Project")

	items = db.relationship("Item", lazy='dynamic')

	def __init__(self, number, description, bill_of_material, vendor, project, creator):
		self.number = number
		self.project = project
		self.description = description
		self.bill_of_material = bill_of_material
		self.vendor = vendor
		self.creator = creator
	

app/models/project.py
import enum
import datetime
from app import db


project_tags = db.Table('project_tag',
	db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True, nullable=False),
	db.Column('project_id', db.String(15), db.ForeignKey('project.id'), primary_key=True, nullable=False)
)


class ProjectMemberRole(enum.Enum):
	PROJECTMANAGER = 'Project Manager'
	ENGINEER = 'Engineer'
	SALES = 'Sales'


class ProjectMemberStatus(enum.Enum):
	ACTIVE = 'Active'
	DEACTIVE = 'Deactive'


class ProjectMember(db.Model):
	__tablename__ = 'project_member'
	project_id = db.Column(db.String(15), db.ForeignKey('project.id'), primary_key=True)
	user_id = db.Column(db.String(10), db.ForeignKey('user.id'), primary_key=True)
	role = db.Column(db.Enum(ProjectMemberRole), nullable=False, default=ProjectMemberRole.ENGINEER)
	status = db.Column(db.Enum(ProjectMemberStatus), nullable=False, default=ProjectMemberStatus.DEACTIVE)
	creator_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)

	project = db.relationship("Project")
	user = db.relationship("User", foreign_keys=[user_id])
	creator = db.relationship("User", foreign_keys=[creator_id])
	created_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)

	def __init__(self, project, user, role, status, created_time, creator):
		self.project = project
		self.user = user
		self.role = role
		self.status = status
		self.created_time = created_time
		self.creator = creator


class ProjectLocation(db.Model):
	__tablename__ = 'project_location'
	project_id = db.Column(db.String(15), db.ForeignKey('project.id'), primary_key=True)
	project = db.relationship("Project")
	location_id = db.Column(db.String(20), db.ForeignKey('location.id'), primary_key=True)
	location = db.relationship("Location")
	creator_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)
	creator = db.relationship('User')
	created_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)

	def __init__(self, project, location, creator):
		self.project = project
		self.location = location
		self.creator = creator


class ProjectStatus(enum.Enum):
	INPROGRESS = 'Inprogress'
	MAINTAINANCE = 'Maintainance'
	COMPLETED = 'Completed'


class Project(db.Model):
	id = db.Column(db.String(15), primary_key=True, nullable=False)
	name = db.Column(db.String(60), nullable=False)
	description = db.Column(db.Text, nullable=False)
	goal = db.Column(db.Text, nullable=False)
	created_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
	updated_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
	status = db.Column(db.Enum(ProjectStatus), nullable=False)
	progress = db.Column(db.Integer)
	agreement = db.Column(db.Text, nullable=False)
	creator_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)
	creator = db.relationship('User')

	tags = db.relationship('Tag', secondary=project_tags, backref=db.backref('projects', lazy='dynamic'))

	members = db.relationship('ProjectMember', lazy='dynamic')

	locations = db.relationship("ProjectLocation", lazy='dynamic')
	files = db.relationship('ProjectFile', lazy='dynamic')
	customers = db.relationship('Customer', lazy='dynamic')
	orders = db.relationship('Order', lazy='dynamic')

	def __init__(self, id, name, description, goal, status, progress, agreement, creator, updated_time=datetime.datetime.utcnow()):
		self.id = id
		self.name = name
		self.description = description
		self.goal = goal
		self.status = status
		self.progress = progress
		self.agreement = agreement
		self.creator = creator
		self.updated_time = updated_time

	@property
	def label_style(self):
		label_styles = {
			ProjectStatus.COMPLETED: 'label label-success',
			ProjectStatus.INPROGRESS: 'label label-warning',
			ProjectStatus.MAINTAINANCE: 'label label-info'
		}
		return label_styles[self.status]


class ProjectFileType(enum.Enum):
	TOPOLOGY = 'Topology'
	AGREEMENT = 'Agreement'
	PRODUCTORDER = 'Product Order'
	BILLOFMATERIAL = 'Bill of Material'
	OTHER = 'Other'

class ProjectFile(db.Model):
	id = db.Column(db.Integer, primary_key=True, autoincrement=True, nullable=False)
	type = db.Column(db.Enum(ProjectFileType), nullable=False, default=ProjectFileType.OTHER)
	name = db.Column(db.String(50), nullable=False)
	object_name = db.Column(db.String(150))
	object_url = db.Column(db.String(150))
	description = db.Column(db.Text)
	uploaded_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)
	
	uploader_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)
	uploader = db.relationship('User')
	project_id = db.Column(db.String(15), db.ForeignKey('project.id'), nullable=False)
	project = db.relationship('Project', backref='roles')

	def __init__(self, name, type, description, object_name, project, uploader, object_url=None):
		self.name = name
		self.type = type
		self.description = description
		self.object_name = object_name
		self.project = project
		self.uploader = uploader
		self.object_url = object_url

app/views/project.py
from flask import render_template, abort, redirect, request, url_for, Blueprint, abort
import flask_login
from app import app, db, login_manager, upload_file
from app.models import Project, ProjectFile, ProjectMember, ProjectLocation, Customer, Order, Item,\
                    ItemLocation, ItemStatus, MaterialType, ProjectFileType, IndexWarrantyType, Material, Location
from app.forms import ProjectForm, OrderForm, CustomerForm, UploadForm, ItemForm
import datetime

project = Blueprint('project', __name__)


@project.route('/', methods=['GET'])
@flask_login.login_required
def index():
    projects = Project.query.all()
    user = flask_login.current_user
    return render_template('project/index.html', user=user, projects=projects, page='project')


# --- Create ---
@project.route('/create', methods=['GET', 'POST'])
@flask_login.login_required
def create():
    form = ProjectForm(request.form)
    if request.method == 'GET':
        return render_template('project/add.html', form=form, page='project')
        
    if request.method == 'POST':
        project = Project(id=form.id.data, 
                        name=form.name.data, 
                        description=form.description.data, 
                        goal=form.goal.data,
                        progress=form.progress.data, 
                        agreement=form.agreement.data,
                        status=form.status.data,
                        creator=flask_login.current_user,
                        updated_time=str(datetime.datetime.utcnow()))
        db.session.add(project)
        db.session.commit()
    return redirect(url_for('project.index'))


# --- Detail ---
@project.route('/<id>', methods=['GET'])
@flask_login.login_required
def get(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/detail/index.html', project=project, page='project')


@project.route('/<id>/detail/edit', methods=['GET', 'POST'])
@flask_login.login_required
def detail_edit(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    
    if request.method == 'GET':
        form = ProjectForm(obj=project)
        return render_template('project/detail/edit.html', project=project, form=form, page='project')
    
    form = ProjectForm(request.form)
    if request.method == 'POST':
        project.name = form.name.data
        project.description = form.description.data
        project.updated_time = str(datetime.datetime.utcnow())
        db.session.merge(project)
        db.session.commit()
    return redirect(url_for('project.get', id=project.id))


# --- Order ---
@project.route('/<id>/order', methods=['GET'])
@flask_login.login_required
def order(id=None):
    project = Project.query.filter_by(id=id).first()
    orders = Order.query.filter_by(project=project).all()
    return render_template('project/order/index.html', project=project, orders=orders, page='project')


@project.route('/<id>/order/add', methods=['GET', 'POST'])
@flask_login.login_required
def order_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = OrderForm(request.form)
    if request.method == 'GET':
        return render_template('project/order/add.html', form=form, page='project')

    if request.method == 'POST':
        order = Order(number=form.number.data,
                    project=project,
                    description=form.description.data,
                    bill_of_material=form.bill_of_material.data,
                    vendor=form.vendor.data,
                    creator=flask_login.current_user)
        db.session.add(order)
        db.session.commit()
    return redirect(url_for('project.order', id=project.id))


@project.route('/<id>/order/edit', methods=['GET', 'POST'])
@flask_login.login_required
def order_edit(id=None):
    return render_template('project/order/edit.html', project=project, page='project')


# --- Customer ---
@project.route('/<id>/customer', methods=['GET'])
@flask_login.login_required
def customer(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    customers = Customer.query.filter_by(project=project).all()
    return render_template('project/customer/index.html', project=project, customers=customers, page='project')


@project.route('/<id>/customer/add', methods=['GET', 'POST'])
@flask_login.login_required
def customer_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = CustomerForm(request.form)
    if request.method == 'GET':
        return render_template('project/customer/add.html', form=form, page='project')

    if request.method == 'POST':
        customer = Customer(firstname=form.firstname.data,
                            lastname=form.lastname.data,
                            location=form.location.data,
                            telephone=form.telephone.data,
                            email=form.email.data,
                            description=form.description.data,
                            project=project,
                            creator=flask_login.current_user)
        
        db.session.add(customer)
        db.session.commit()
    return redirect(url_for('project.customer', id=project.id))


# --- Member ---
@project.route('/<id>/member', methods=['GET'])
@flask_login.login_required
def member(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    members = ProjectMember.query.filter_by(project=project).all()
    return render_template('project/member/index.html', project=project, members=members, page='project')


@project.route('/<id>/member/manage', methods=['GET'])
@flask_login.login_required
def member_manage(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/member/manage.html', project=project, page='project')


@project.route('/<id>/member/add', methods=['GET'])
@flask_login.login_required
def member_add(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    return render_template('project/member/add.html', project=project, page='project')


# --- Item ---
@project.route('/<id>/item', methods=['GET'])
@flask_login.login_required
def item(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    orders = project.orders.all()
    materials = MaterialType.query.all()
    itemlocation = ItemLocation.query.all()
    return render_template('project/item/index.html', project=project, orders=orders, materials=materials, itemlocation=itemlocation, page='project')


@project.route('/<id>/item/add', methods=['GET', 'POST'])
@flask_login.login_required
def item_add(id=None):
    project = Project.query.filter_by(id=id).first()
    form = ItemForm(request.form)
    if not project:
        abort(404)
    
    choices = [(b.number, b.model) for b in Material.query.order_by(Material.model).all()]
    form.material.choices = choices
    materials = Material.query.all()
    
    choices = [(c.id, c.number) for c in Order.query.filter_by(project_id=id).all()]
    form.order.choices = choices
    orders = Order.query.all()

    choices = [(d.id, d.name) for d in IndexWarrantyType.query.order_by(IndexWarrantyType.name).all()]
    form.warranty_type.choices = choices
    warranty_types = IndexWarrantyType.query.all()

    # choices = [(e.id, e.name) for e in ProjectLocation.query.filter_by(project=id).all()]
    choices = [(e.id, e.name) for e in Location.query.order_by(Location.name).all()]
    form.location.choices = choices
    locations = IndexWarrantyType.query.all()
    if request.method == 'GET':
        return render_template('project/item/add.html', form=form, materials=materials, orders=orders, warranty_types=warranty_types, locations=locations, page='project')

    if request.method == 'POST':
        material = Material.query.filter_by(number=form.material.data).first()
        order = Order.query.filter_by(id=form.order.data).first()
        warranty_type = IndexWarrantyType.query.filter_by(id=form.warranty_type.data).first()
        location = Location.query.filter_by(id=form.location.data).first()
        item = Item(serial_number=form.serial_number.data,
                    box_number=form.box_number.data,
                    name=form.name.data,
                    warranty_expire=form.warranty_expire.data,
                    sap=form.sap.data,
                    material=material,
                    order=order,
                    warranty_type=warranty_type)
        
        itemlocation = ItemLocation(location=location,
                                    item=item,
                                    status=form.status.data,
                                    equipment=form.equipment.data,
                                    creator=flask_login.current_user)
        print '<location: {}, item: {}>'.format(location.id, item.serial_number)
        db.session.add(item)
        db.session.add(itemlocation)
        db.session.commit()
    return redirect(url_for('project.item', id=project.id))

# @project.route('/<id>/item/setting', methods=['GET'])
# @flask_login.login_required
# def item_setting(id=None):
#     project = Project.query.filter_by(id=id).first()
#     if not project:
#         abort(404)
#     items = Order.query.filter_by(project=project).all()
#     return render_template('project/item/setting.html', project=project, items=items, page='project')


# --- Location ---
@project.route('/<id>/location', methods=['GET'])
@flask_login.login_required
def location(id=None):
    project = Project.query.filter_by(id=id).first()
    if not project:
        abort(404)
    locations = ProjectLocation.query.filter_by(project=project).all()

app/templates/project/order/add.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><h3>Order</h3></span>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal group-border-dashed" method="POST">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Number</label>
                                <div class="col-sm-6">
                                    {{ form.number(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Description</label>
                                <div class="col-sm-6">
                                    {{ form.description(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Bill of Material</label>
                                <div class="col-sm-6">
                                    {{ form.bill_of_material(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Vendor</label>
                                <div class="col-sm-6">
                                    {{ form.vendor(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/project/order/edit.html
<h1>This member order edit page</h1>

app/templates/project/order/index.html
<!-- extend base layout -->
{% extends "base.html" %}



{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tab-container">
                    <ul class="nav nav-tabs">
                        <li><a href="{{url_for('project.get', id=project.id)}}">Detail</a></li>
                        <li class="active"><a href="javascript:void(0);">Orders</a></li>
                        <li><a href="{{url_for('project.customer', id=project.id)}}">Customers</a></li>
                        <li><a href="{{url_for('project.member', id=project.id)}}">Members</a></li>
                        <li><a href="{{url_for('project.item', id=project.id)}}">Items</a></li>
                        <li><a href="{{url_for('project.location', id=project.id)}}">Locations</a></li>
                        <li><a href="{{url_for('project.files', id=project.id)}}">Files</a></li>
                    </ul>
                    
                    <div class="tab-content">
                        <div id="order" class="tab-pane active cont">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <a href="{{ url_for('project.order_add', id=project.id) }}" class="btn btn-primary pull-right" role="button">Add</a>
                                    <span><h3>{{project.name}} #{{project.id}}</h3></span>
                                </div>
                                <div class="panel-body">
                                    <form class="form-horizontal group-border-dashed">
                                        <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Product Order</th>
                                                    <th>Bill of Material</th>
                                                    <th>Vendor</th>
                                                    <th>Desciption</th>
                                                    <th>Date</th>
                                                    <th>Created by</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for order in orders %}
                                                <tr>
                                                    <td>{{order.number}}</td>
                                                    <td>{{order.bill_of_material}}</td>
                                                    <td>{{order.vendor}}</td>
                                                    <td>{{order.description}}</td>
                                                    <td>{{order.created_time}}</td>
                                                    <td>{{order.creator.fullname}}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}