app/models/material.py
import datetime
from app import db

material_tags = db.Table('material_tag',
	db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'), primary_key=True, nullable=False),
	db.Column('material_number', db.String(20), db.ForeignKey('material.number'), primary_key=True, nullable=False)
	)

class Material(db.Model):
	number = db.Column(db.String(20), primary_key=True, nullable=False)
	series = db.Column(db.String(45), nullable=False)
	model = db.Column(db.String(20), nullable=False)
	serial_length = db.Column(db.Integer, nullable=False)
	description = db.Column(db.Text)


	os_id = db.Column(db.Integer, db.ForeignKey('operating_system.id'), default=None)
	os = db.relationship('OperatingSystem')
	brand_id = db.Column(db.Integer, db.ForeignKey('brand.id'), nullable=False)
	brand = db.relationship('Brand')
	creator_id = db.Column(db.String(10), db.ForeignKey('user.id'), nullable=False)
	creator = db.relationship('User')
	created_time = db.Column(db.DateTime, nullable=False, default=datetime.datetime.utcnow)

	items = db.relationship('Item', lazy='dynamic')
	tags = db.relationship('Tag', secondary=material_tags,
			backref=db.backref('materials'), lazy='dynamic')

	type_id = db.Column(db.Integer, db.ForeignKey('material_type.id'), nullable=False)
	type = db.relationship('MaterialType')

	def __init__(self, number, brand, series, model, serial_length, type, os=None, description=None, creator=None):
		self.number = number
		self.brand = brand
		self.series = series
		self.model = model
		self.serial_length = serial_length
		self.os = os
		self.brand = brand
		self.type = type
		self.description = description
		if creator is not None:
			self.creator = creator
			

class MaterialType(db.Model):
	id = db.Column(db.Integer, autoincrement=True, primary_key=True)
	name = db.Column(db.String(30), nullable=False)
	description = db.Column(db.Text)
	font_color = db.Column(db.String(20), default='#000000')
	cell_color = db.Column(db.String(20), default='#FFFFFF')
	
	materials = db.relationship('Material', lazy='dynamic')

	def __init__(self, name, description, font_color=None, cell_color=None):
		self.name = name
		self.description = description
		self.font_color = font_color
		self.cell_color = cell_color

	# def __repr__(self):
	# 	return "<MaterialType: id={}, name={}, description={}, font_color={}, cell_color={}>".format(
	# 		self.id, self.name, self.description, self.font_color, self.cell_color)
	def __repr__(self):
		return '<Type: id=%r, name=%r>' % (self.id, self.name)


class Brand(db.Model):
	id = db.Column(db.Integer, autoincrement=True, primary_key=True)
	name = db.Column(db.String(30), nullable=False)
	description = db.Column(db.Text)

	materials = db.relationship('Material', lazy='dynamic')

	os = db.relationship('OperatingSystem', lazy='dynamic')
	def __init__(self, name, description=None):
		self.name = name
		self.description = description

	def __repr__(self):
		return '<Brand: id=%r, name=%r>' % (self.id, self.name)


class OperatingSystem(db.Model):
	id = db.Column(db.Integer, autoincrement=True, primary_key=True)
	name = db.Column(db.String(30), nullable=False)
	description = db.Column(db.Text)


	brand_id = db.Column(db.Integer, db.ForeignKey('brand.id'))
	brand = db.relationship('Brand')

	materials = db.relationship('Material', lazy='dynamic')
# 	brand = db.relationship('Brand')

	def __init__(self, name, brand, description=None):
		self.name = name
		self.description = description
		self.brand = brand

	def __repr__(self):
		return '<OS: id=%r, name=%r, brand=%r>' % (self.id, self.name, self.brand)

	

app/views/material.py
from flask import render_template, abort, redirect, request, url_for, Blueprint
import flask_login
from app import app, db, login_manager
from app.models import Material, MaterialType, Brand, OperatingSystem
from app.forms import MaterialForm, MaterialTypeForm, MaterialOSForm, MaterialBrandForm


material = Blueprint('material', __name__)


@material.route('/', methods=['GET'])
@flask_login.login_required
def index():
    materials = Material.query.all()
    return render_template('material/index.html', materials=materials, page='material')


@material.route('/<id>', methods=['GET'])
@flask_login.login_required
def get(id=None):
    material = Material.query.filter_by(number=id).first()
    if not material:
        abort(404)
    return render_template('material/detail.html', material=material, page='material')


@material.route('/create', methods=['GET', 'POST'])
@flask_login.login_required
def create():
    form = MaterialForm(request.form)
    choices = [(c.id, c.name) for c in MaterialType.query.order_by(MaterialType.name).all()]
    form.type.choices = choices
    types = MaterialType.query.all()

    choices = [(d.id, d.name) for d in Brand.query.order_by(Brand.name).all()]
    form.brand.choices = choices
    brands = Brand.query.all()
    if request.method == 'GET':
        return render_template('material/add.html', form=form, types=types, brands=brands, page='material')

    if request.method == 'POST':
        brand = Brand.query.filter_by(id=form.brand.data).first()
        type = MaterialType.query.filter_by(id=form.type.data).first()
        material = Material(number=form.number.data, 
                            brand=brand,
                            series=form.series.data,
                            model=form.model.data,
                            serial_length=form.serial_length.data,
                            os=form.os.data,
                            type=type,
                            description=form.description.data,
                            creator=flask_login.current_user)
        db.session.add(material)
        db.session.commit()
    return redirect(url_for('material.index'))


@material.route('/<id>/edit', methods=['GET', 'POST'])
@flask_login.login_required
def edit(id=None):
    form = MaterialForm(request.form)
    material = Material.query.filter_by(number=id).first()
    if not material:
        abort(404)
    if request.method == 'GET':
        form = MaterialForm(obj=material)
        return render_template('material/edit.html', material=material, form=form, page='material')
    
    if request.method == 'POST':
        # material.number = form.number.data
        # material.brand = form.brand.data
        material.series = form.series.data
        material.model = form.model.data
        material.serial_length = form.serial_length.data
        material.description = form.description.data
        db.session.merge(material)
        db.session.commit()
    return redirect(url_for('material.index'))


@material.route('/type', methods=['GET'])
@flask_login.login_required
def type_index():
    types = MaterialType.query.all()
    return render_template('material/type/index.html', types=types, page='material')


@material.route('/type/add', methods=['GET', 'POST'])
@flask_login.login_required
def type_add():
    form = MaterialTypeForm(request.form)
    if request.method == 'GET':
        return render_template('material/type/add.html', form=form, page='material')

    if request.method == 'POST':
        materialtype = MaterialType(
                    name=form.name.data,
                    description=form.description.data,
                    font_color=form.font_color.data,
                    cell_color=form.cell_color.data)
        db.session.add(materialtype)
        db.session.commit()
    return redirect(url_for('material.type_index'))


@material.route('/type/<id>', methods=['GET', 'POST'])
@flask_login.login_required
def type_edit(id=None):
    materialtype = MaterialType.query.filter_by(id=id).first()
    if not materialtype:
        abort(404)
    
    if request.method == 'GET':
        form = MaterialTypeForm(obj=materialtype)
        return render_template('material/type/edit.html', materialtype=materialtype, form=form, page='material')
    
    form = MaterialTypeForm(request.form)
    if request.method == 'POST':
        materialtype.name = form.name.data
        materialtype.description = form.description.data
        materialtype.font_color = form.font_color.data
        materialtype.cell_color = form.cell_color.data
        db.session.merge(materialtype)
        db.session.commit()
    return redirect(url_for('material.type_index'))

# --- Operation System ---
@material.route('/os', methods=['GET'])
@flask_login.login_required
def os_index():
    multi_os = OperatingSystem.query.all()
    return render_template('material/os/index.html', multi_os=multi_os, page='material')


@material.route('/os/add', methods=['GET', 'POST'])
@flask_login.login_required
def os_add():
    form = MaterialOSForm(request.form)
    choices = [(d.id, d.name) for d in Brand.query.order_by(Brand.name).all()]
    form.brand.choices = choices
    brands = Brand.query.all()
    if request.method == 'GET':
        return render_template('material/os/add.html', form=form, page='material')

    if request.method == 'POST':
        brand = Brand.query.filter_by(id=form.brand.data).first()
        os = OperatingSystem(name=form.name.data,
                            brand=brand,
                            description=form.description.data)
        db.session.add(os)
        db.session.commit()
    return redirect(url_for('material.os_index'))


@material.route('/os/<id>', methods=['GET', 'POST'])
@flask_login.login_required
def os_edit(id=None):
    os = OperatingSystem.query.filter_by(id=id).first()
    if not os:
        abort(404)
    
    if request.method == 'GET':
        form = MaterialOSForm(obj=os)
        return render_template('material/os/edit.html', os=os, form=form, page='material')
    
    form = MaterialOSForm(request.form)
    if request.method == 'POST':
        os.name = form.name.data
        os.description = form.description.data
        db.session.merge(os)
        db.session.commit()
    return redirect(url_for('material.os_index'))


# --- Brand ---
@material.route('/brand', methods=['GET'])
@flask_login.login_required
def brand_index():
    brands = Brand.query.all()
    return render_template('material/brand/index.html', brands=brands, page='material')


@material.route('/brand/add', methods=['GET', 'POST'])
@flask_login.login_required
def brand_add():
    form = MaterialBrandForm(request.form)
    if request.method == 'GET':
        return render_template('material/brand/add.html', form=form, page='material')

    if request.method == 'POST':
        brand = Brand(name=form.name.data,
                    description=form.description.data)
        db.session.add(brand)
        db.session.commit()
    return redirect(url_for('material.brand_index'))


@material.route('/brand/<id>', methods=['GET', 'POST'])
@flask_login.login_required
def brand_edit(id=None):
    brand = Brand.query.filter_by(id=id).first()
    if not brand:
        abort(404)
    
    if request.method == 'GET':
        form = MaterialBrandForm(obj=brand)
        return render_template('material/brand/edit.html', brand=brand, form=form, page='material')
    
    form = MaterialBrandForm(request.form)
    if request.method == 'POST':
        brand.name = form.name.data
        brand.description = form.description.data
        db.session.merge(brand)
        db.session.commit()
    return redirect(url_for('material.brand_index'))

app/templates/material/add.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><h3>Material</h3></span>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal group-border-dashed" method="POST">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Material Number</label>
                                <div class="col-sm-6">
                                    {{ form.number(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Brand</label>
                                <div class="col-sm-6">
                                    {{ form.brand(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Series</label>
                                <div class="col-sm-6">
                                    {{ form.series(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Model</label>
                                <div class="col-sm-6">
                                    {{ form.model(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Serial length</label>
                                <div class="col-sm-6">
                                    {{ form.serial_length(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Type</label>
                                <div class="col-sm-6">
                                    {{ form.type(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Description</label>
                                <div class="col-sm-6">
                                    {{ form.description(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/material/detail.html
<!-- extend base layout -->
{% extends "base.html" %}


 
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a href="{{ url_for('material.edit',id=material.number) }}" class="btn btn-primary pull-right" role="button">Edit</a>
                        <span><h3>Material</h3></span>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal group-border-dashed">
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Material Number</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.number}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Brand</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.brand.name}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Series</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.series}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Model</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.model}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Serial length</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.serial_length}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Operation System</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.os}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Type</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.type.name}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Description</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.description}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><b>Created by</b></label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.creator.fullname}}</p>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/material/edit.html
<!-- extend base layout -->
{% extends "base.html" %}


 
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <span><h3>Material</h3></span>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal group-border-dashed" method="POST">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Material Number</label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.number}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Brand</label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.brand.name}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Type</label>
                                <div class="col-sm-6">
                                    <p class="form-control-static">{{material.type.name}}</p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Series</label>
                                <div class="col-sm-6">
                                    {{ form.series(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Model</label>
                                <div class="col-sm-6">
                                    {{ form.model(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Serial length</label>
                                <div class="col-sm-6">
                                    {{ form.serial_length(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Description</label>
                                <div class="col-sm-6">
                                    {{ form.description(class="form-control") }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-3">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/material/index.html
<!-- extend base layout -->
{% extends "base.html" %}
{% block content %}
<div class="am-content">
    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tab-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="javascript:void(0);">Material</a></li>
                        <li><a href="{{url_for('material.type_index')}}">Type</a></li>
                        <li><a href="{{url_for('material.os_index')}}">OS</a></li>
                        <li><a href="{{url_for('material.brand_index')}}">Brand</a></li>
                    </ul>

                    <div class="tab-content">
                        <div id="detail" class="tab-pane active cont">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <a href="{{ url_for('material.create') }}" class="btn btn-primary pull-right" role="button">Add</a>
                                    <span><h3>Material</h3></span>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label"></label>
                                        <div class="col-sm-6">
                                            <div id="new-search-area" class="text-center"></div>
                                        </div>
                                    </div>

                                    <table id="table" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Material Number</th>
                                                <th>Brand</th>
                                                <th>Series</th>
                                                <th>Model</th>
                                                <th>Type</th>
                                                <th>Operation System</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for material in materials %}
                                            <tr>
                                                <td><a href="{{ url_for('material.get', id=material.number) }}">{{material.number}}</a></td>
                                                <td><a href="{{ url_for('material.get', id=material.number) }}">{{material.brand.name}}</a></td>
                                                <td>{{material.series}}</td>
                                                <td>{{material.model}}</td>
                                                <td>{{material.type.name}}</td>
                                                <td>{{material.os.name}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}